export const LOCALSTATIONDATA = [
  {
    callLetters: "WCRF",
    url: "http://playerservices.streamtheworld.com/api/livestream-redirect/WCRFFMAAC.aac",
    name: "103.3 FM - Cleveland",
    lat: 41.29679,
    lng: -81.65726,
  },
  {
    callLetters: "KMBI",
    url: "http://playerservices.streamtheworld.com/api/livestream-redirect/KMBIFMAAC.aac",
    name: "107.9 FM - Spokane",
    lat: 47.57051,
    lng: -117.08334,
  },
  {
    callLetters: "WFCM",
    url: "http://playerservices.streamtheworld.com/api/livestream-redirect/WFCMFMAAC.aac",
    name: "1200 AM - Nashville",
    lat: 36.208333,
    lng: -86.8725,
  },
  {
    callLetters: "WMBW",
    url: "http://playerservices.streamtheworld.com/api/livestream-redirect/WMBWFMAAC.aac",
    name: "88.9 FM - Chattanooga",
    lat: 34.96217,
    lng: -85.37786,
  },
  {
    callLetters: "WMFT",
    url: "http://playerservices.streamtheworld.com/api/livestream-redirect/MB2AAC.aac",
    name: "88.9 FM - Tuscaloosa/Birmingham",
    lat: 33.33871,
    lng: -87.35886,
  },
  {
    callLetters: "WDLM",
    url: "http://playerservices.streamtheworld.com/api/livestream-redirect/WDLMFMAAC.aac",
    name: "89.3 FM - East Moline",
    lat: 41.54747,
    lng: -90.47485,
  },
  {
    callLetters: "WRMB",
    url: "http://playerservices.streamtheworld.com/api/livestream-redirect/WRMBFMAAC.aac",
    name: "89.3 FM - South Florida",
    lat: 26.51796,
    lng: -80.17034,
  },
  {
    callLetters: "WGNB",
    url: "http://playerservices.streamtheworld.com/api/livestream-redirect/WGNBFMAAC.aac",
    name: "89.3 FM - Zeeland",
    lat: 42.83721,
    lng: -85.98831,
  },
  {
    callLetters: "KMBN",
    url: "http://playerservices.streamtheworld.com/api/livestream-redirect/MB2AAC.aac",
    name: "89.7 FM - Las Cruces",
    lat: 32.2783,
    lng: -106.91191,
  },
  {
    callLetters: "WMBI",
    url: "http://playerservices.streamtheworld.com/api/livestream-redirect/WMBIFMAAC.aac",
    name: "90.1 FM - Chicago",
    lat: 41.9278,
    lng: -88.00695,
  },
  {
    callLetters: "WJSO",
    url: "http://playerservices.streamtheworld.com/api/livestream-redirect/MB2AAC.aac",
    name: "90.1 FM - Pikeville",
    lat: 37.46444,
    lng: -82.54528,
  },
  {
    callLetters: "WKES",
    url: "http://playerservices.streamtheworld.com/api/livestream-redirect/WKESFMAAC.aac",
    name: "91.1 FM - St. Petersburg",
    lat: 28.07937,
    lng: -82.04075,
  },
  {
    callLetters: "WFCM",
    url: "http://playerservices.streamtheworld.com/api/livestream-redirect/WFCMFMAAC.aac",
    name: "91.7 FM - Murfreesboro",
    lat: 35.80019,
    lng: -86.62123,
  },
  {
    callLetters: "WCDC",
    url: "http://playerservices.streamtheworld.com/api/livestream-redirect/MB2AAC.aac",
    name: "950 AM - Charleston",
    lat: null,
    lng: null,
  },
  {
    callLetters: "WGNR",
    url: "http://playerservices.streamtheworld.com/api/livestream-redirect/WGNRFMAAC.aac",
    name: "97.9 FM - Indianapolis",
    lat: 40.06235,
    lng: -85.70924,
  },
  {
    callLetters: "WFCM",
    url: "https://playerservices.streamtheworld.com/api/livestream-redirect/WFCMFMAAC.aac",
    name: "98.7 FM - Nashville",
    lat: 35.80019,
    lng: -86.62123,
  },
];
